OPEN-ENT-NG/nextcloud

src/main/java/fr/openent/nextcloud/controller/DocumentsController.java, src/main/java/fr/openent/nextcloud/core/constants/Field.java, src/main/java/fr/openent/nextcloud/helper/EbHelper.java, src/main/java/fr/openent/nextcloud/helper/EventBusHelper.java, src/main/java/fr/openent/nextcloud/helper/FileHelper.java, src/main/java/fr/openent/nextcloud/helper/MessageResponseHandler.java, src/main/java/fr/openent/nextcloud/service/DocumentsService.java, src/main/java/fr/openent/nextcloud/service/ServiceFactory.java, src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java
Adding two new routes to API. The first one will be used to move a file from Nextcloud to workspace and the second one will be used to copy a file from Nextcloud to workspace. Nextcloud and Workspace need to belong to the same user.
Both of following routes tested with Postman.
[ PUT ] /files/user/:userid/copy/workspace
[ PUT ] /files/user/:userid/move/workspace
[ DRIV-26 ]
https://entsupport.gdapublic.fr/projects/DRIV/issues/DRIV-26
=> feat(nextcloud): #DRIV-26 add new route for copying and moving files from nextcloud

src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java
Listing file was ended up in bad request due to space in the url in backend. Fix was to replace space by %20 before calling nextcloud API.
Tested with postman, no more bad request.
No ticket.
=> fix(list): fixing bad request due to not encoded spaces in url

src/main/java/fr/openent/nextcloud/controller/DocumentsController.java, src/main/resources/public/ts/services/__test__/nextcloud.service.test.ts, src/main/resources/public/ts/services/nextcloud-event.service.ts, src/main/resources/public/ts/services/nextcloud.service.ts, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts, src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts, src/main/resources/public/ts/utils/workspace-entcore.utils.ts
Depuis l'espace doc, on peut glisser et déposer un document depuis le nextcloud dans n'importe quel dossier dans "mes documents personnels"
En faisant cette action, on supprime le document qu'on a glissé et déposé dans le nextcloud (étant donné qu'on fait un déplacement)
Un fix sur le comportement de la sélection des documents ont été fait également
https://entsupport.gdapublic.fr/browse/DRIV-38
=> feat: #DRIV-38 add drag file nextcloud to workspace

src/main/resources/public/ts/services/__test__/nextcloud.service.test.ts, src/main/resources/public/ts/services/nextcloud.service.ts, src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
⚠ si possible, merge la PR https://github.com/OPEN-ENT-NG/nextcloud/pull/27 avant de lire celle-ci 
Depuis l'espace doc, on peut glisser et déposer un document depuis le l'espace doc "mes documents personnels" dans l'arborescence nextcloud
En faisant cette action, on supprime le document qu'on a glissé et déposé dans l'espace documentaire "mes documents personnels" (étant donné qu'on fait un déplacement)
https://entsupport.gdapublic.fr/browse/DRIV-19
=> feat: #DRIV-19 add drag file workspace to nextcloud

src/main/java/fr/openent/nextcloud/controller/DocumentsController.java, src/main/java/fr/openent/nextcloud/helper/StringHelper.java, src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java, src/main/resources/public/ts/models/nextcloud.folder.model.ts, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar.sniplet.ts
Before this update, renaming a file wasn't working. Plus symbol and spaces was misinterpreted by Nextcloud server.
To fix that, we modified front by removing pre-encoding and we are now managing encoding in back.
Checked on browser.
No ticket, it's part of the core.
=> fix(rename): renaming file is now working with spaces and plus symbol

src/main/java/fr/openent/nextcloud/controller/DocumentsController.java, src/main/java/fr/openent/nextcloud/core/constants/Field.java, src/main/java/fr/openent/nextcloud/service/DocumentsService.java, src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java
Following PR #27. Before this update, the result of the API call was just the status of the move or copy. Now API call return every information about the file in case of succes, and the error message if it fails.
API Documentation : https://entconf.gdapublic.fr/display/DRIV/Nextcloud+Documents+API
Both of following routes tested with Postman.
[ PUT ] /files/user/:userid/copy/workspace
[ PUT ] /files/user/:userid/move/workspace
[ DRIV-38 ]
https://entsupport.gdapublic.fr/projects/DRIV/issues/DRIV-38
=> feat(move): #DRIV-38 API now return everything about the file moved or copied

src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
It is now possible to drop multiple files into workspace from Nextcloud. Before this update, the API was able to handle multiple move but the front was not giving the rights parameters.
Checked on browser.
[ DRIV-38 ]
https://entsupport.gdapublic.fr/projects/DRIV/issues/DRIV-38
=> feat(nextcloud): #DRIV-38 Move multiple files from Nextcloud to workspace is now working

src/main/java/fr/openent/nextcloud/core/constants/Field.java, src/main/java/fr/openent/nextcloud/core/enums/EventBusActions.java, src/main/java/fr/openent/nextcloud/core/enums/WorkspaceEventBusActions.java, src/main/java/fr/openent/nextcloud/helper/EventBusHelper.java, src/main/java/fr/openent/nextcloud/helper/MessageResponseHandler.java, src/main/java/fr/openent/nextcloud/model/NextcloudFolder.java, src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts, src/main/resources/public/ts/utils/workspace-entcore.utils.ts
Following of #12. It is now possible to move and copy folder and not anymore just files. We also add the possibility to move / copy multiple files with the same name from workspace to nextcloud without overwriting it after the first copy / move.
When we use this new feature, it can bring some inconveniences to the user. As it enables you to move as much file as you want from nextcloud to workspace, this action can end up creating a lot of files in your workspace.
In this context of move / copy, we mainly use  : 
`moveDocumentToWorkspace / copyDocumentToWorkspace` : these 2 functions take a list of path (from nextloud) to copy or move the corresponding files / folders in the workspace. 
From here we will handle the things differently depending on the link target type (folder or file). 
In …
=> feat(move): #DRIV-26 move is available for folders

src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/ts/nextcloud.behaviours.ts, src/main/resources/public/ts/services/nextcloud.service.ts, src/main/resources/public/ts/sniplets/virtual-media-library.ts, src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts, src/main/resources/public/ts/utils/nextcloud-documents.utils.ts, src/main/resources/public/ts/utils/workspace-entcore.utils.ts
Reprend la PR https://github.com/CGI-OPEN-ENT-NG/infra-front/pull/7 
Cette PR utilise l'implémentation de virtual folder pour que le composant media-library
[DRAFT] Une version sur l'entcore du package.json sera modifié pour ajouté le composant virtual folder
Prerequis config (tech part) : 
https://entsupport.gdapublic.fr/browse/DRIV-26
=> feat(virtual-folder): #DRIV-25 add virtual folder implementation

src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts, src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
…
Following of #40, when we dropped files from nextcloud to workspace, and then clicked in the workspace tree, the selected folder was not the right one, it was the parent folder.
The fix main fix was to update manually the openedFolder in the scope.
Tested on browser (EDGE). 
[ DRIV-38 ]
https://entsupport.gdapublic.fr/browse/DRIV-38
=> fix(move): #DRIV-38 move from nextcloud to workspace now select the right folder in the tree

src/main/java/fr/openent/nextcloud/controller/NextcloudController.java, src/main/java/fr/openent/nextcloud/core/constants/Field.java, src/main/java/fr/openent/nextcloud/security/Access.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/workspace-nextcloud-content.html, src/main/resources/public/ts/services/__test__/nextcloud.service.test.ts, src/main/resources/public/ts/services/nextcloud.service.ts, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
Permet de mettre en évidence l'url de nextcloud pour les utilisateurs qui ONT ACCESS au Nextcloud pour basculier au client nextcloud
Doc : https://entconf.gdapublic.fr/display/DRIV/Nextcloud+Config+API#NextcloudConfigAPI-getnextcloudconfigURL
https://entsupport.gdapublic.fr/browse/DRIV-42
=> feat(url): #DRIV-42 add nextcloud url display into workspace

src/main/java/fr/openent/nextcloud/controller/DocumentsController.java, src/main/java/fr/openent/nextcloud/core/constants/Field.java, src/main/java/fr/openent/nextcloud/core/enums/NextcloudHttpMethod.java, src/main/java/fr/openent/nextcloud/core/enums/WorkspaceEventBusActions.java, src/main/java/fr/openent/nextcloud/helper/EventBusHelper.java, src/main/java/fr/openent/nextcloud/service/DocumentsService.java, src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java, src/main/resources/public/ts/core/enums/documents-type.ts, src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
Following #28 We are now able to drop folders from workspace to nextcloud.
We added the corresponding changes to the API and added the copy API too.
Documentation: https://entconf.gdapublic.fr/pages/viewpage.action?spaceKey=DRIV&title=Nextcloud+Documents+API
[ DRIV - 19 ]
https://entsupport.gdapublic.fr/projects/DRIV/issues/DRIV-19
=> feat(move): #DRIV-19 move folders from WS to NC is now working

src/main/java/fr/openent/nextcloud/controller/DocumentsController.java, src/main/java/fr/openent/nextcloud/core/constants/Field.java, src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java, src/main/resources/public/ts/services/__test__/nextcloud.service.test.ts, src/main/resources/public/ts/services/nextcloud.service.ts, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
Context: We wanted to add the possibility to move a file within nextcloud's forlders.
https://user-images.githubusercontent.com/101819152/176392864-caa246ab-a367-46c1-a8ea-92664bbc4911.mp4
It is now possible to move a nextcloud file into a nextcloud folder. It is working as the rename option.
If the file name already exists in the target folder, the operation will fail.
[ DRIV-45 ]
https://entsupport.gdapublic.fr/projects/DRIV/issues/DRIV-45
=> feat(move): #DRIV-45 add move nextcloud option

src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar.sniplet.ts
Context: we wanted the tree to be updated when we deleted, moved and renamed folders from nextcloud
Follwing #8 We added the update in the two functions rename and remove and delete. 
The tree is now updated.
[ DRIV-23 ]
https://entsupport.gdapublic.fr/browse/DRIV-23
=> fix(delete): #DRIV-23 delete folders now update tree

src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
We updated the target of the HTML class update, as a result the right element is selected in the workspace tree.
[ DRIV-48 ]
https://entsupport.gdapublic.fr/browse/DRIV-48
=> fix(switch): #DRIV-48 select folder in workspace is now working

src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
Add selected folders in the move API call id list. Bedore folders was not supported for move, so the front was ignoring them.
[ DRIV-19 ]
https://entsupport.gdapublic.fr/browse/DRIV-19
=> fix(move): #DRIV-19 select multiples folders for move is now working

src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
Following #47, before this update, moving a folder from workspace to nextcloud was not applying the update to the nextcloud tree.
[ DRIV-19 ]
https://entsupport.gdapublic.fr/browse/DRIV-19
=> fix(move): #DRIV-19 move folder now update nextcloud tree

src/main/resources/public/sass/global/components/sniplets/_nextcloud-content.scss, src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/workspace-nextcloud-content.html
Open an empty folder in Nextcloud now display an emptyscreen if the folder is empty.
[ Driv-58 ]
=> fix(empty-state): #DRIV-58 add css empty state nextcloud

src/main/java/fr/openent/nextcloud/helper/EventBusHelper.java, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar-share.sniplet.ts, src/main/resources/public/ts/utils/workspace-entcore.utils.ts
Toolbar display is now working properly after sharing a file.
We also removed the import button import when switching in nextcloud context.
[ DRIV-58 ]
=> fix(toolbar): #DRIV-56 display toolbar is now working properly

src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
Updated selected folders and document from workspace so the toolbar no longer persists when we swipe to nextcloud context.
[ DRIV-58 ]
=> fix(toolbar): #DRIV-56 toggle toolbar display is now working

src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
When you switch from nextcloud to workspace subfolders, the view is now working and not displaying anymore wrong files.
[ DRIV-58 ]
=> fix(tree): #DRIV-58 switch context is now working for subfolders

src/main/resources/public/ts/models/__mocks__/entcore.ts, src/main/resources/public/ts/models/nextcloud.folder.model.ts, src/main/resources/public/ts/services/__test__/nextcloud.service.test.ts
Sur les environnements de prod/preprod, le workspace utilise la configuration `lazy-loading` (` "publicConf": {
"lazy-mode": true
}
`)
Quand il est activé, les services dans le workspace bascule en mode  ["lazy mode"](https://github.com/opendigitaleducation/infra-front/blob/d2462d2825fdbd059251baeb9545e6a3d6721c62/src/ts/workspace/services.ts#L178) 
[son init](https://github.com/opendigitaleducation/infra-front/blob/d2462d2825fdbd059251baeb9545e6a3d6721c62/src/ts/workspace/services.ts#L1151)
Ce qui altère le comportement et ajoute des objets javascript pas prévu dans le cas où on n'a pas de conviction de faire du "lazy mode" dans leur workspace.
Afin de contrer cette alteration, on ajoute les objets `CacheList` dans chaque item qu'on sollicite pour notre `tree`.
Dans le module workspace …
=> fix(tree): fix tree by adding instruction to disable lazyLoading

src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts
Vu que l'on n'a pas accès au composant folder-tree, j'ai ajouté un event listener au survol de chaque dossier pour ajouter la classe `.droptarget`. Afin de garantir que le feedback est présent sur chaque sous-dossier la fonction est appelée à chaque changement de dossier (en détruisant les anciens listeners puis en les recréant). 
Glisser un fichier/dossier dans un des dossiers de "Documents synchronisés", une bordure en pointillé orange va apparaitre autour du dossier en question.
[DRIV-59](https://jira.support-ent.fr/browse/DRIV-59)
=> fix(drag): #DRIV-59 add drag over feedback

src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/workspace-nextcloud-content.html, src/main/resources/public/ts/core/enums/document-role.ts, src/main/resources/public/ts/models/nextcloud.folder.model.ts, src/main/resources/public/ts/services/__test__/nextcloud.service.test.ts, src/main/resources/public/ts/utils/nextcloud-documents.utils.ts
Before this update, icons was all the same and not displayed according to file role.
[ DRIV-68 ]
https://jira.support-ent.fr/browse/DRIV-68
=> fix(icons): #DRIV-68 display icons depending on file role is now working

src/main/resources/public/ts/services/__test__/nextcloud.service.test.ts, src/main/resources/public/ts/services/nextcloud.service.ts
Fixed url when open file located in nextloud root folder
[ DRIV-24 ] 
https://jira.support-ent.fr/browse/DRIV-24
=> fix(onlyoffice): #DRIV-24 open doc located in root folder is now working

src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar-share.sniplet.ts
Before this update, when using "share and not copy", the file was deleted if the action was cancelled. Now the file stays in the folder if the action is cancelled.
[ DRIV-82 ]
https://jira.support-ent.fr/browse/DRIV-82
=> fix(share): #DRIV-82 cancel file share does not delete file anymore

src/main/java/fr/openent/nextcloud/controller/DocumentsController.java, src/main/java/fr/openent/nextcloud/core/constants/Field.java, src/main/java/fr/openent/nextcloud/service/DocumentsService.java, src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/template/behaviours/sniplet-nextcloud-content/toolbar/workspace-nextcloud-toolbar-delete.html, src/main/resources/public/ts/models/nextcloud-user.model.ts, src/main/resources/public/ts/services/nextcloud.service.ts, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar-share.sniplet.ts, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar.sniplet.ts, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-upload-file.sniplet.ts
Now quota is updated with nextcloud server data and update each time a file is moved or deleted.
An other issue in the quota update was appening while deleting a file. On the ENT side, the delete is permanent because trash for nextcloud is not implemented, but trashbin exits on the nextcloud server. As the feature is not implemented yet, we decided to delete permanently (empty trashbin on server side) each time the user deletre a file. The is the reasons why a new API is implemented. The trash empty action was implemented in an other API in order to anticipate the trashbin feature.
API link: https://confluence.support-ent.fr/display/DRIV/Nextcloud+Documents+API#NextcloudDocumentsAPI-Emptytrash
Without this update, the user's quota was shortened because the trash counts in the user quota …
=> fix(quota): #DRIV-74 update quota calculation method

src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar-share.sniplet.ts
Before this update, sharing a file without copy and cancel it was not updating user info and made nextcloud folder disappear 
[ DRIV-98 ]
https://jira.support-ent.fr/browse/DRIV-98
=> fix(share): #DRIV-98 share a file update correctly user infos

README.md, deployment/nextcloud/conf.j2, deployment/nextcloud/conf.json.template, src/main/java/fr/openent/nextcloud/config/NextcloudConfig.java, src/main/java/fr/openent/nextcloud/model/UserNextcloud.java, src/main/java/fr/openent/nextcloud/service/impl/DefaultUserService.java
Aujourd'hui, quand il y a une création d'un utilisateur de nextcloud depuis l'ENT, son quota est à 2 GB
l'idée est de modifier son quota dynamiquement (en fonction de la configuration).
A rajouter dans la conf nextcloud : 
```
"config": {
...
"endpoint" : {
"ocs-api": "...",
"webdav-api": "..."
},
"quota": "2 GB"
...
}
```
- Mettre une valeur "6 GB" dans la conf quota
- Aller dans l'espace doc avec un compte autorisé à accéder sur nextcloud qui aura son compte nextcloud generé avec 6 GB
https://jira.support-ent.fr/browse/DRIV-99
=> feat(quota): #DRIV-99 add configurable quota value on create user

src/main/resources/i18n/fr.json
Replace i18n nextcloud.url.connect sentence in fr.json file
When in workspace, click on "documents synchronisés", the sentence will appear above the nextcloud folders and must be "Indiquez cette url en configuration Nextcloud pour accéder au service sur tous vos appareils : http://nextcloud:8080/"
[DRIV-50](https://jira.support-ent.fr/browse/DRIV-50)
=> feat(i18n): change nextcloud.url.connect sentence

src/main/java/fr/openent/nextcloud/controller/DocumentsController.java
When selecting files inside a folder and click on download button, the zip files used to take "folderName.zip" name.
Now the zip file is called archive.zip
Go ton "document synchronisés" and try to download multiple files inside a specific folder. The generated zip file should be called "archive.zip"
[DRIV-97](https://jira.support-ent.fr/browse/DRIV-97)
=> feat(download): change zip file name when downloading from within a folder

src/main/resources/i18n/fr.json, src/main/resources/public/template/behaviours/sniplet-nextcloud-folder/workspace-nextcloud-folder.html, src/main/resources/public/ts/models/__test__/nextcloud-user.model.test.ts, src/main/resources/public/ts/models/nextcloud-user.model.ts, src/main/resources/public/ts/services/__test__/nextcloud-user.service.test.ts
The progress bar directive which displays the quota of user's space allocation used the data.total number send by OCS nextcloud API. But a percentage of error was added to this value which made the compute false. For example, if the user had 10 GB of storage, the API sent 8152707889 bytes (for the total) and then the progress bar displayed 7.7 Go because of the calcultation (this.total = data.total/ (1024 * 1024)).
Instead, i use data.quota value which represents better the user's storage. (this.total = data.quota / (1024 * 1024));
Moreover, if user has illimited capacity, the directive is replaced by a span tag to display "Espace illimité".
Finally, the model nextcloud-user.model.ts was changed and quota properties like "free", "relative" and "quota" were delated because unused by the …
=> feat(directive): #DRIV-100 fit progress bar quota value to nextcloud server user storage space

package.json, src/main/resources/public/ts/shared/services/index.ts, src/main/resources/public/ts/shared/services/nextcloud.preferences.ts, src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
In workspace, the default view for nextcloud ("documents synchonisés") is the ICON one. Now, when the user switches in LIST view, this action sets a "viewMode" preference to store the view and then he can switch from "dossier partagés" to nextcloud and the choosen view remains the same. It also works when he gets back to the icon view. 
Update Axios mock-adapter to avoid test errors (has no default export) in dev mode.
In workspace, go to "documents synchronisés", change the view mode with the button on the right, then click on "documents partagés". If you come back to "documents synchronisés", the view you had chosen is still the same. You can try it by refreshing the browser too. 
[DRIV-102](https://jira.support-ent.fr/browse/DRIV-102)
=> feat(preference): #DRIV-102 create user preference for nextcloud view 
