OPEN-ENT-NG/nextcloud

src/main/resources/public/template/behaviours/sniplet-nextcloud-content/toolbar/workspace-nextcloud-toolbar-properties.html
src/main/resources/public/template/behaviours/sniplet-nextcloud-content/toolbar/workspace-nextcloud-toolbar.html
src/main/resources/public/ts/models/__mocks__/entcore.ts
src/main/resources/public/ts/services/__test__/nextcloud-user.service.test.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar.sniplet.ts

Ce [commit ](https://github.com/OPEN-ENT-NG/nextcloud/commit/402496b749a69179d3fd05e3996e77b86a2a05e2) est également à prendre en compte de cette PR

feat(properties): #DRIV-21 add properties workspace feat to nextcloud

---

src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/workspace-nextcloud-content.html
src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/workspace-nextcloud-upload-file.html
src/main/resources/public/template/behaviours/sniplet-nextcloud-folder/workspace-nextcloud-folder.html
src/main/resources/public/template/behaviours/workspace-nextcloud.html
src/main/resources/public/ts/nextcloud.behaviours.ts
src/main/resources/public/ts/services/nextcloud.service.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-upload-file.sniplet.ts

Cette feature permet d'upload un fichier (reprend presque le flow d'upload dans l'espace doc)
Possibilité de la merge sur DEV mais ne sera pas encore fonctionnel (wip back API)

feat(upload): #DRIV-19 add upload document nextcloud

---

src/main/java/fr/openent/nextcloud/controller/DocumentsController.java
src/main/java/fr/openent/nextcloud/core/constants/Field.java
src/main/java/fr/openent/nextcloud/helper/Attachment.java
src/main/java/fr/openent/nextcloud/helper/FileHelper.java
src/main/java/fr/openent/nextcloud/helper/FutureHelper.java
src/main/java/fr/openent/nextcloud/helper/Metadata.java
src/main/java/fr/openent/nextcloud/service/DocumentsService.java
src/main/java/fr/openent/nextcloud/service/ServiceFactory.java
src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java

feat(nextcloud): #DRIV-19 add new route for uploading file on nextcloud PR

feat(nextcloud): #DRIV-19 add new route for uploading file on nextcloud

---

src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts

Refactor code pour empêcher du code/instruction qui s'execute en masse
Correction au niveau de la sélection de documents personnels qui ne se passe pas parfois
S'assurer qu'en cliquant sur document synchroniser et "documents personnels" l'affichage se passe bien.
Pas de ticket, c'est un fix et perfomance

fix(listener): remove dupicate add listener

---

src/main/java/fr/openent/nextcloud/controller/NextcloudController.java
src/main/java/fr/openent/nextcloud/core/constants/WorkflowRight.java
src/main/java/fr/openent/nextcloud/core/enums/WorkflowActions.java
src/main/resources/public/ts/nextcloud.behaviours.ts
src/main/resources/public/ts/rights.ts
src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts

Ajout droit "view" pour autoriser l'accès au composant nextcloud (arborescence) dans l'espace documentaire
https://entconf.gdapublic.fr/display/DRIV/Configuration+des+droits+Workflow
https://entsupport.gdapublic.fr/browse/DRIV-37

feat(workflow): #DRIV-37 add workflow right access nextcloud view

---

src/main/java/fr/openent/nextcloud/controller/UserController.java
src/main/java/fr/openent/nextcloud/helper/WorkflowHelper.java
src/main/java/fr/openent/nextcloud/security/CanAccessNextcloud.java

Cette PR reprend la PR https://github.com/OPEN-ENT-NG/nextcloud/pull/17
Un ajout de code a été ajouté pour gérer la sécurité sur la route pour créer un compte et générer un token
Même phase de test mais  côté API (tester la route [GET - /user/:userid/provide/token] -> userid étant l'identifiant de l'utilisateur neo4j

feat(workflow): #DRIV-37 add workflow right access nextcloud secure API

---

src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java

Fixing bug in PR #20 . Juste fixing a bug. We reported one bug. During file move, the answer from the API was sent before all the files were properly deleted from Nextcloud. 
Fix : We wait for the delete part to be completed before completing the promise.
Route tested with Postman
[ DRIV-19 ]
https://entsupport.gdapublic.fr/projects/DRIV/issues/DRIV-19
[ PUT ] /files/user/:userid/nextcloud/move

fix(nextcloud): #DRIV-19 wait for delete to be completed on NC before sending response

---

src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java

Upload file ended up in bad request due to space in the url in backend. Fix was to replace space by %20 before calling nextcloud API.
Tested with postman, no more bad request.
[ DRIV-41 ]
https://entsupport.gdapublic.fr/projects/DRIV/issues/DRIV-41

fix(upload): #DRIV-41 fixing bad request due to not encoded spaces in url

---

src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts

Quand on clique sur l'arborescence de nextcloud, on fait défiler les dossiers qui sont dans le nextcloud
On reclique ensuite sur "mes documents perso'" et quand on décide de cliquer sur un des dossiers dans le nextcloud, ca nous appelle le contenu de la racine au lieu du dossier en question
Aucune, c'est un bug détecté par un dev

fix(tree): fix init document content path not adapted w/ nextcloud tree

---

src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java

Two fixes here. The major one is the update is the way we retrive the name of the file. Now we use the last part of the path, se we don't duplicate data and keep the final path until the end. Second update here is to remove double slash in nextcloud call when the API is call with a path starting with "/".
Tested with postman, no more bad request.
[ DRIV-19]
https://entsupport.gdapublic.fr/projects/DRIV/issues/DRIV-19

fix(move): #DRIV-19 change method to retrieve file name

---

src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar.sniplet.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-upload-file.sniplet.ts

Quand on fait une action pour chaque document/dossier (cad delete, propriété, upload fichier), le select se perd à chaque resynchronisation 
Le fix concerne sur le fait qu'on ne perd pas le select
Aucun, c'est un bug détecté par un dev qui a été effectué rapidement

fix(select): fix action nextcloud document select unbind

---

src/main/resources/public/template/behaviours/sniplet-nextcloud-content/toolbar/share/share-documents-options.html
src/main/resources/public/template/behaviours/sniplet-nextcloud-content/toolbar/share/share.html
src/main/resources/public/template/behaviours/sniplet-nextcloud-content/toolbar/share/workspace-nextcloud-toolbar-share.html
src/main/resources/public/template/behaviours/sniplet-nextcloud-content/toolbar/workspace-nextcloud-toolbar.html
src/main/resources/public/ts/services/nextcloud.service.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar-share.sniplet.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar.sniplet.ts

Modifying front to add share option :
- updating HTML to include share button
- adding copy to workspace function in service
- handling click on share button in the sniplet
[ DRIV-39 ]
https://entsupport.gdapublic.fr/projects/DRIV/issues/DRIV-39

feat(share): #DRIV-39 add share nextcloud to workspace

---

LICENSE
README.md

docs: add new licence and technical description

---

src/main/resources/i18n/en.json
src/main/resources/i18n/fr.json

changement titre typo
https://entsupport.gdapublic.fr/browse/DRIV-25

fix(virtual-folder): #DRIV-25 change typo

---

src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts

Move a file from nexcloud to nextcloud with the same name file is now handled. Before this update, if the target folder contained a file with the same name as the moved file, the moved file was deleted.
[ DRIV-45 ]
https://entsupport.gdapublic.fr/browse/DRIV-45

fix(move): #DRIV-45 move a file in folder with same file is now handled

---

src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts

Moving a file under a parent folder is now working for files from nextcloud to nextcloud.
[ DRIV-55 ] 
https://entsupport.gdapublic.fr/browse/DRIV-55

fix(move): #DRIV-55 move file under a parent folder in NC is now working

---

src/main/resources/public/template/behaviours/create-folder/folder-creation.html
src/main/resources/public/template/behaviours/sniplet-nextcloud-folder/workspace-nextcloud-folder.html
src/main/resources/public/ts/sniplets/folder/nextcloud-folder.sniplet.ts

Following #59. Cancel folder creation now clean name. 
[ DRIV-56 ]
https://entsupport.gdapublic.fr/browse/DRIV-56

fix(create): #DRIV-56 cancel folder creation now clean folder name

---

src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java

Sharing files is now working for folders.
[ DRIV-40 ] 
https://entsupport.gdapublic.fr/browse/DRIV-40

fix(share): #DRIV-40 copy folders is now working

---

src/main/resources/public/template/behaviours/sniplet-nextcloud-content/toolbar/share/share-documents-options.html

Cancel button is now working in share view
[ DRIV-58 ]

fix(share): #DRIV-56 cancel share is now working

---

src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar-share.sniplet.ts

Cancel button is now working.
-[x] Cancel share 
[ DRIV-58 ]

fix(button): #DRIV-58 cancel sharing is now working

---

src/main/java/fr/openent/nextcloud/controller/DocumentsController.java
src/main/java/fr/openent/nextcloud/service/DocumentsService.java
src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java
src/main/resources/public/ts/services/__test__/nextcloud.service.test.ts
src/main/resources/public/ts/services/nextcloud.service.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar.sniplet.ts

Le téléchargement de dossier ne marchant pas, j'ai ajouté la possibilité de le faire en ajoutant un query param **isFolder** (bool) sur la route GET /nextcloud/files/user/:userid/file/:fileName/download
**Si isFolder = true :**
la route renvoie un Dossier.zip contenant le dossier.
**Sinon :**
Téléchargement du fichier comme précédemment.
Pour le front j'ai ajouté le query param **isFolder** sur la méthode [getFile](https://github.com/OPEN-ENT-NG/nextcloud/pull/70/files#diff-f7515dac19b9c12683ae22e23cceca9f6a0428c872027f7426b97a78a140eed3L87)
Puis modifié les tests en conséquence ([ici](https://github.com/OPEN-ENT-NG/nextcloud/pull/70/files#diff-319aec8eee2bcc0ce24ff11aef81ce396d63b62f255ad004e803793e1ae56f0dR131))
[ DRIV-64 ](https://jira.support-ent.fr/browse/DRIV-64)

fix(download): #DRIV-64 download folder

---

src/main/resources/i18n/en.json
src/main/resources/i18n/fr.json
src/main/resources/public/sass/global/components/_index.scss
src/main/resources/public/sass/global/components/toasts.scss
src/main/resources/public/template/behaviours/sniplet-nextcloud-content/toolbar/workspace-nextcloud-toolbar-delete.html
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-toolbar.sniplet.ts

- Updated description text in delete confirmation modal
- Added a feedback message when deleting folder/document
[DRIV-60](https://jira.support-ent.fr/browse/DRIV-60)

fix(delete): #DRIV-60 add feedback message and update typo when confirming the deletion

---

src/main/resources/public/sass/global/components/sniplets/_nextcloud-content.scss
src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/workspace-nextcloud-content.html

Added a class to make the article component responsive to the size of the screen and the number of documents it contains.
[DRIV-69]()

fix(css): #DRIV-69 fix responsive for documents list

---

src/main/resources/public/template/behaviours/sniplet-nextcloud-content/toolbar/workspace-nextcloud-toolbar-delete.html

fix(typo): fix duplicate closing tag

---

src/main/java/fr/openent/nextcloud/service/DocumentsService.java
src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java
src/main/java/fr/openent/nextcloud/service/impl/DefaultUserService.java
src/test/java/fr/openent/nextcloud/service/impl/UserServiceTest.java

Connect to nextcloud server is working even if the user token is expired in our database. Now before every connection, we check the token validity and update it if necessary.
[ DRIV-67 ]
https://jira.support-ent.fr/browse/DRIV-67

feat(token): #DRIV-67 connect to nextcloud even if token is expired

---

src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts

Fix compile: remove private visibility on methods.
Functionality tested again: OK

fix: fixed compilation errors

---

src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java

You can now upload mulitple files with the same name. Before it was not possible, now a number is added after the name, depending on the number of duplicate.
[ DRIV-73 ]
https://jira.support-ent.fr/browse/DRIV-73

fix(upload): #DRIV-73 upload multiple files with the same name is working

---

src/main/resources/public/template/behaviours/sniplet-nextcloud-folder/workspace-nextcloud-folder.html
src/main/resources/public/ts/sniplets/workspace-nextcloud-folder.sniplet.ts

Display the workspace quota and buttons under the workspace folders
Display the nextcloud quota and buttons under the nextcloud folders
Must correspond to the attached image on the Jira ticket.
[DRIV-51](https://jira.support-ent.fr/browse/DRIV-51)

feat(quota): #DRIV-51 display the workspace quota under the workspace folders

---

src/main/java/fr/openent/nextcloud/helper/DateHelper.java
src/main/java/fr/openent/nextcloud/model/Document.java
src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/views/icons.html
src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/views/list.html
src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/workspace-nextcloud-content.html
src/main/resources/public/ts/core/enums/view-mode.ts
src/main/resources/public/ts/models/nextcloud.folder.model.ts
src/main/resources/public/ts/services/__test__/nextcloud.service.test.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-view-icons.sniplet.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-view-list.sniplet.ts

add view list for nextcloud documents (iso workspace) : split content in 2 template (list and icons)
add lastModified date to nextcloud document
click on list view icon, you should see the documents in list with 4 columns : name, owner name, last modified date and file size.
[DRIV-65](https://jira.support-ent.fr/browse/DRIV-65)

feat(list): #DRIV-65 add view list

---

src/main/resources/public/ts/models/__test__/nextcloud-user.model.test.ts
src/main/resources/public/ts/models/nextcloud-user.model.ts

Return 2 digits after the decimal point for the quota used in progress bar.
Prevent showing empty progress bar for quota < 0.05 Go
Fill the synchronized folder with small files and you should see little use progress bar instead of no progress.
[DRIV-74](https://jira.support-ent.fr/browse/DRIV-74)

fix(quota): #DRIV-74 return two digits after the decimal point for the quota used

---

src/main/java/fr/openent/nextcloud/controller/DocumentsController.java
src/main/java/fr/openent/nextcloud/service/impl/DefaultDocumentsService.java
src/main/resources/public/ts/services/nextcloud.service.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
src/main/resources/public/ts/sniplets/folder/nextcloud-folder.sniplet.ts
src/test/java/fr/openent/nextcloud/service/impl/DocumentServiceTest.java

Upload files with special char is now working
[ DRIV-66 ]
https://jira.support-ent.fr/browse/DRIV-66

fix(upload): #DRIV-66 import file with specials chars is now working

---

src/main/java/fr/openent/nextcloud/controller/DocumentsController.java
src/main/java/fr/openent/nextcloud/core/constants/Field.java

Download a folder including multiples folders now display "archive" download name and not the user's name
[ DRIV-77 ]
https://jira.support-ent.fr/browse/DRIV-77

fix(download): #DRIV-77 update the name of zip folder

---

src/main/resources/public/template/behaviours/sniplet-nextcloud-content/content/views/icons.html

Adding an overlay when a file or folder is selected
[ DRIV-80 ]
https://jira.support-ent.fr/browse/DRIV-80

fix(select): #DRIV-80 add overlay when a file or folder is selected

---

gradle.properties
gulpfile.js
package.json
src/main/resources/view-src/nextcloud.html

prepare 4.6.0 migration
compile and check with new springboard

chore: prepare 4.6.0 migration

---

src/main/resources/i18n/en.json
src/main/resources/i18n/fr.json
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-content.sniplet.ts
src/main/resources/public/ts/sniplets/content/workspace-nextcloud-upload-file.sniplet.ts

Before this update, if an error occurs while uploading file, no feedback was sent to the user. Now, a notify is sent with the error message
[ DRIV-83 ]
https://jira.support-ent.fr/browse/DRIV-83

fix(upload): #DRIV-83 notify if an error happen during file upload

---

src/main/resources/public/ts/sniplets/content/workspace-nextcloud-upload-file.sniplet.ts

Progress bar is now updated when a file is uploaded
[ DRIV-74 ]
https://jira.support-ent.fr/browse/DRIV-74

fix(quota): #DRIV-74 update quota progress bar

---

src/main/resources/i18n/en.json
src/main/resources/i18n/fr.json

Update error message if upload fails
Check #93 
[ DRIV - 83 ]
https://jira.support-ent.fr/browse/DRIV-83

fix(upload): #DRIV-83 update error message

---

frontend/src/components/BwLimits/index.tsx
frontend/src/components/BwLimits/style.ts
frontend/src/components/SyncFolder/index.tsx
frontend/src/providers/GlobalProvider/index.tsx
frontend/src/providers/GlobalProvider/utils.ts
frontend/src/styles/theme.ts

This PR introduces a new `BwLimits` component that provides input fields for setting bandwidth limits (upload and download) for both reception and emission. The inputs include validation to block unwanted values, such as non-numeric inputs and negative numbers.
- **Two Input Fields**: 
- One for reception (download limit).
- One for emission (upload limit).
- **Input Validation**: 
- Blocks non-numeric values (e.g., strings).
- Prevents negative numbers.
- Replaces empty values or values starting with `0` with a valid `0`.
- **Logic Externalization**: The validation and formatting logic for input values has been externalized into a utility function, ensuring the code is clean, reusable, and maintainable.
This component ensures that only valid numeric values are accepted for bandwidth …

feat: #DRIV-141 add bandwidth inputs component

---

backend/src/main/resources/i18n/en.json
backend/src/main/resources/i18n/fr.json
frontend/src/components/BwLimits/style.ts
frontend/src/components/DeletableChip/index.tsx
frontend/src/components/ExcludedExtensions/index.tsx
frontend/src/components/ExcludedExtensions/style.ts
frontend/src/containers/MainPage/index.tsx
frontend/src/containers/MainPage/style.ts
frontend/src/providers/GlobalProvider/index.tsx
frontend/src/providers/GlobalProvider/types.ts
frontend/src/styles/theme.ts

This PR introduces two key user interface improvements:
1. **Save Confirmation Alert**:
- A confirmation alert is displayed when an item is saved, providing better feedback to the user about the success of the action.
2. **Tooltip for Long Extensions**:
- A tooltip is automatically shown when the extension text overflows and is truncated with ellipsis, allowing the user to view the full text by hovering over it.
- The tooltip follows the mouse cursor for a smoother user experience.
[DRIV-148](https://jira.support-ent.fr/browse/DRIV-148)

feat: #DRIV-148 add alert on save and tooltip on long extensions

---

backend/src/main/java/fr/openent/nextcloud/controller/NextcloudDesktopController.java
backend/src/main/java/fr/openent/nextcloud/core/constants/WorkflowRight.java
backend/src/main/java/fr/openent/nextcloud/core/enums/WorkflowActions.java
backend/src/main/java/fr/openent/nextcloud/security/AdminDesktop.java

This Pull Request introduces **workflow rights** for the `/nextcloud/desktop/config` route, specifically for the `GET` and `PUT` endpoints.
- Added workflow rights for the **GET** endpoint on `/nextcloud/desktop/config`, ensuring proper access control.
- Added workflow rights for the **PUT** endpoint on `/nextcloud/desktop/config`, securing update actions.
- Updated the `WorkflowActions` enum to include the appropriate permissions for these actions.
- Ensured that access to these endpoints is restricted based on user roles and permissions.
[DRIV-149](https://jira.support-ent.fr/browse/DRIV-149)

feat: #DRIV-149 add security on new route

---

src/main/java/fr/openent/nextcloud/helper/FileHelper.java

Modification d'une fonction non utilisée en Vert.x 4.5 qui empêche l'import d'un fichier ZIP
https://jira.support-ent.fr/browse/DRIV-117

fix(upload): #DRIV-117 fix upload zip file function

---

angularjs/src/ts/utils/workspace-entcore.utils.ts
frontend/package.json
frontend/scripts/package.cjs
frontend/src/app/root/index.tsx
frontend/src/main.tsx
frontend/src/stores/rights/store.ts

fix: update dependencies to new @edifice.io packages
